/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pvs;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;


/**
 * Generated by gradle.
 *
 * @author Christian
 */
public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
